export const PROJECTS = [
  {
    id: 1,
    title: "ShopFlow E-Commerce",
    dev: "Alex Chen",
    description:
      "Full-stack e-commerce platform with real-time inventory management, Stripe payments, and multi-vendor support",
    longDescription:
      "A comprehensive e-commerce solution built with modern web technologies. Features include real-time inventory management, Stripe payment integration, admin dashboard, order tracking, and responsive design for all devices. The platform supports multi-vendor functionality and includes advanced search with filters.",
    category: "fullstack",
    buildTime: "4 months",
    techStack: ["React", "Node.js", "MongoDB", "Stripe", "Redux"],
    rating: 4.8,
    ratingCount: 2341,
    thumbnail: "http://static.photos/technology/320x240/10",
    screenshots: [
      "http://static.photos/technology/640x360/11",
      "http://static.photos/technology/640x360/12",
      "http://static.photos/technology/640x360/13",
    ],
    github: "#",
    liveDemo: "#",
    featured: true,
    trending: true,
    recent: true,
    features: [
      "Product catalog with advanced filters",
      "Secure Stripe checkout",
      "Real-time order tracking",
      "Admin analytics dashboard",
      "Multi-vendor support",
      "Mobile-responsive design",
    ],
  },
  {
    id: 2,
    title: "FitTrack Pro",
    dev: "Alex Chen",
    description:
      "Fitness tracking mobile app with workout plans, nutrition logging, and wearable device integration",
    longDescription:
      "A feature-rich fitness tracking app that helps users monitor workouts, set goals, and track progress over time. Includes social features, workout plans, nutrition logging, and integration with popular wearable devices.",
    category: "mobile",
    buildTime: "3 months",
    techStack: ["React Native", "Firebase", "Redux", "Charts"],
    rating: 4.6,
    ratingCount: 1823,
    thumbnail: "http://static.photos/wellness/320x240/20",
    screenshots: [
      "http://static.photos/wellness/640x360/21",
      "http://static.photos/wellness/640x360/22",
      "http://static.photos/wellness/640x360/23",
    ],
    github: "#",
    liveDemo: "#",
    featured: true,
    trending: true,
    recent: false,
    features: [
      "Workout logging & history",
      "Custom fitness plans",
      "Nutrition tracking",
      "Social feed & challenges",
      "Wearable device sync",
      "Progress analytics",
    ],
  },
  {
    id: 3,
    title: "DesignKit UI Library",
    dev: "Alex Chen",
    description:
      "Open-source React component library with 50+ accessible, customizable components and dark mode support",
    longDescription:
      "An open-source UI component library for React with 50+ accessible, customizable components. Built with Tailwind CSS, supports dark mode, RTL, and comes with comprehensive documentation and Storybook stories.",
    category: "opensource",
    buildTime: "6 months",
    techStack: ["React", "TypeScript", "Tailwind", "Storybook"],
    rating: 4.9,
    ratingCount: 5672,
    thumbnail: "http://static.photos/minimal/320x240/30",
    screenshots: [
      "http://static.photos/minimal/640x360/31",
      "http://static.photos/minimal/640x360/32",
      "http://static.photos/minimal/640x360/33",
    ],
    github: "#",
    liveDemo: "#",
    featured: false,
    trending: true,
    recent: true,
    features: [
      "50+ accessible components",
      "Dark mode support",
      "TypeScript first",
      "Storybook documentation",
      "Tree-shakeable",
      "Customizable themes",
    ],
  },
  {
    id: 4,
    title: "CloudNotes",
    dev: "Alex Chen",
    description:
      "Real-time collaborative note-taking app with markdown, code snippets, and offline sync",
    longDescription:
      "A collaborative note-taking application that supports real-time editing, markdown, code snippets, and file attachments. Features include workspaces, team sharing, version history, and offline mode with sync.",
    category: "web",
    buildTime: "2 months",
    techStack: ["Next.js", "Socket.io", "PostgreSQL", "AWS"],
    rating: 4.7,
    ratingCount: 3456,
    thumbnail: "http://static.photos/workspace/320x240/40",
    screenshots: [
      "http://static.photos/workspace/640x360/41",
      "http://static.photos/workspace/640x360/42",
      "http://static.photos/workspace/640x360/43",
    ],
    github: "#",
    liveDemo: "#",
    featured: true,
    trending: false,
    recent: true,
    features: [
      "Real-time collaboration",
      "Markdown editor",
      "Code snippet support",
      "Version history",
      "Offline mode",
      "Team workspaces",
    ],
  },
  {
    id: 5,
    title: "PortfolioForge",
    dev: "Alex Chen",
    description:
      "Drag-and-drop portfolio builder for developers with curated templates and one-click deploy",
    longDescription:
      "A drag-and-drop portfolio builder designed specifically for developers. Choose from curated templates, customize sections, and deploy a stunning portfolio in minutes. Supports custom domains and analytics.",
    category: "uiux",
    buildTime: "5 months",
    techStack: ["Vue.js", "D3.js", "Express", "MongoDB"],
    rating: 4.5,
    ratingCount: 1234,
    thumbnail: "http://static.photos/education/320x240/50",
    screenshots: [
      "http://static.photos/education/640x360/51",
      "http://static.photos/education/640x360/52",
      "http://static.photos/education/640x360/53",
    ],
    github: "#",
    liveDemo: "#",
    featured: false,
    trending: false,
    recent: true,
    features: [
      "Drag-and-drop builder",
      "Developer-focused templates",
      "Custom domain support",
      "Built-in analytics",
      "SEO optimization",
      "One-click deploy",
    ],
  },
  {
    id: 6,
    title: "FreelanceHub CRM",
    dev: "Alex Chen",
    description:
      "All-in-one CRM for freelancers with invoicing, time tracking, and automated payment reminders",
    longDescription:
      "An all-in-one CRM designed for freelancers to manage clients, invoices, projects, and communications. Features time tracking, contract templates, and automated payment reminders.",
    category: "freelance",
    buildTime: "3.5 months",
    techStack: ["React", "GraphQL", "Prisma", "Stripe"],
    rating: 4.4,
    ratingCount: 892,
    thumbnail: "http://static.photos/office/320x240/60",
    screenshots: [
      "http://static.photos/office/640x360/61",
      "http://static.photos/office/640x360/62",
      "http://static.photos/office/640x360/63",
    ],
    github: "#",
    liveDemo: "#",
    featured: false,
    trending: true,
    recent: false,
    features: [
      "Client management",
      "Invoice generation",
      "Time tracking",
      "Contract templates",
      "Payment reminders",
      "Project pipeline",
    ],
  },
  {
    id: 7,
    title: "PixelEditor Online",
    dev: "Alex Chen",
    description:
      "Browser-based image editor with layer support, 50+ filters, drawing tools, and offline capability",
    longDescription:
      "A powerful browser-based image editor with layer support, filters, drawing tools, and export options. Works offline with service workers and supports PSD import/export.",
    category: "web",
    buildTime: "7 months",
    techStack: ["TypeScript", "Canvas API", "Web Workers", "PWA"],
    rating: 4.3,
    ratingCount: 2100,
    thumbnail: "http://static.photos/craft/320x240/70",
    screenshots: [
      "http://static.photos/craft/640x360/71",
      "http://static.photos/craft/640x360/72",
      "http://static.photos/craft/640x360/73",
    ],
    github: "#",
    liveDemo: "#",
    featured: false,
    trending: true,
    recent: false,
    features: [
      "Layer system",
      "50+ filters & effects",
      "Drawing tools",
      "PSD support",
      "Offline capability",
      "Plugin system",
    ],
  },
  {
    id: 8,
    title: "MealPrep AI",
    dev: "Alex Chen",
    description:
      "AI-powered meal planning app with personalized plans, grocery lists, and nutritional tracking",
    longDescription:
      "Smart meal planning app that generates personalized weekly meal plans based on dietary preferences, budget, and nutritional goals. Includes grocery list generation and recipe step-by-step guides.",
    category: "mobile",
    buildTime: "4.5 months",
    techStack: ["Flutter", "Python", "TensorFlow", "Firebase"],
    rating: 4.7,
    ratingCount: 3200,
    thumbnail: "http://static.photos/food/320x240/80",
    screenshots: [
      "http://static.photos/food/640x360/81",
      "http://static.photos/food/640x360/82",
      "http://static.photos/food/640x360/83",
    ],
    github: "#",
    liveDemo: "#",
    featured: true,
    trending: true,
    recent: true,
    features: [
      "AI meal generation",
      "Dietary preferences",
      "Budget planning",
      "Grocery lists",
      "Recipe guides",
      "Nutritional tracking",
    ],
  },
  {
    id: 9,
    title: "DevBlog Engine",
    dev: "Alex Chen",
    description:
      "Minimal blogging platform for developers with MDX, syntax highlighting, and RSS feeds",
    longDescription:
      "A minimalist blogging engine built for developers who love to write. Supports MDX, code syntax highlighting, og-image generation, and RSS feeds. Self-hosted and lightweight.",
    category: "opensource",
    buildTime: "1.5 months",
    techStack: ["Next.js", "MDX", "Vercel", "Tailwind"],
    rating: 4.6,
    ratingCount: 1800,
    thumbnail: "http://static.photos/minimal/320x240/90",
    screenshots: [
      "http://static.photos/minimal/640x360/91",
      "http://static.photos/minimal/640x360/92",
      "http://static.photos/minimal/640x360/93",
    ],
    github: "#",
    liveDemo: "#",
    featured: false,
    trending: false,
    recent: true,
    features: [
      "MDX support",
      "Code highlighting",
      "OG image generation",
      "RSS feeds",
      "SEO optimized",
      "Self-hosted",
    ],
  },
  {
    id: 10,
    title: "TaskWave Kanban",
    dev: "Alex Chen",
    description:
      "Kanban board with drag-and-drop, team collaboration, and GitHub/Slack integrations",
    longDescription:
      "A beautiful Kanban-style project management tool with drag-and-drop, team assignments, due dates, and integrations with GitHub, Slack, and more.",
    category: "fullstack",
    buildTime: "3 months",
    techStack: ["React", "Node.js", "Socket.io", "Redis"],
    rating: 4.5,
    ratingCount: 1500,
    thumbnail: "http://static.photos/workspace/320x240/100",
    screenshots: [
      "http://static.photos/workspace/640x360/101",
      "http://static.photos/workspace/640x360/102",
      "http://static.photos/workspace/640x360/103",
    ],
    github: "#",
    liveDemo: "#",
    featured: true,
    trending: false,
    recent: false,
    features: [
      "Drag-and-drop boards",
      "Team assignments",
      "Due date tracking",
      "GitHub integration",
      "Slack notifications",
      "Time estimates",
    ],
  },
];
