import {
  shapeLogo,
  shape1,
  shape3,
  shape4,
  shape5,
  shape6,
  shape7,
  shape8,
  shape9,
  shape10,
  shape11,
  shape12,
} from "@/assets/projects/shape";
import {
  chlLogo,
  chl1,
  chl2,
  chl3,
  chl4,
  chl5,
  chl6,
} from "@/assets/projects/chl";
import { rvsLogo, rvs1, rvs2, rvs3, rvs4 } from "@/assets/projects/rvs";
import {
  tableoLogo,
  tableo1,
  tableo2,
  tableo3,
  tableo4,
  tableo5,
} from "@/assets/projects/tableo";
import {
  swiftLogo,
  swift1,
  swift2,
  swift3,
  swift4,
  swift5,
  swift6,
  swift7,
  swift8,
  swift9,
} from "@/assets/projects/swift";
import { scanLogo, scan1, scan2, scan3 } from "@/assets/projects/scan";
import { projLogo, proj1, proj2, proj3 } from "@/assets/projects/proj";
import { taskLogo, task1, task2, task3 } from "@/assets/projects/task";
import {
  agriLogo,
  agri1,
  agri2,
  agri3,
  agri4,
  agri5,
  agri6,
  agri7,
  agri8,
  agri9,
  agri10,
  agri11,
  agri12,
  agri13,
  agri14,
  agri15,
  agri16,
  agri17,
  agri18,
  agri19,
  agri20,
} from "@/assets/projects/agri";

export const PROJECTS = [
  {
    id: 1,
    title: "S.H.A.P.E: Mobile Learning Application for Special Needs Education",
    description:
      "S.H.A.P.E is a mobile learning application developed for students under Special Needs Education (SNED). The application allows students to access educational activities and interactive games even without internet connection through offline functionality. It includes a total of 20+ interactive educational games designed to enhance learning engagement. Integrated with a web management system, teachers can upload lessons, monitor student progress, manage curriculum and semesters, and track achievements through an awards system. The platform also includes automated grading and progress tracking features.",
    category: "mobile",
    buildTime: "4mo",
    techStack: ["Flutter", "Dart", "Flame Engine", "SQLite", "Git & GitHub"],
    thumbnail: shapeLogo,
    screenshots: [shape8, shape9, shape10, shape11, shape12],
    github: "https://github.com/Madrigal-Carl/shape_mobile",
    liveDemo: "",
    featured: true,
    completedAt: "2025-12-01",
    features: [
      "Offline gameplay functionality",
      "Interactive educational activities",
      "Student progress tracking",
      "Awards and achievement system",
    ],
    contributions: [
      "Frontend development (UI and feature implementation)",
      "Backend integration and API handling",
      "Development of 5+ interactive educational games",
    ],
  },
  {
    id: 2,
    title: "S.H.A.P.E Admin & Learning Management System",
    description:
      "The S.H.A.P.E web application serves as the administrative and educational management platform for teachers and school administrators. Teachers can upload activities and lessons, monitor student performance, manage semesters and curriculum structures, and review automated grading results. The system also includes student tracking, awards management, and centralized content management integrated with the mobile application.",
    category: "web",
    buildTime: "5mo",
    techStack: [
      "Laravel",
      "Livewire",
      "PHP",
      "MySQL",
      "Tailwind CSS",
      "Git & GitHub",
    ],
    thumbnail: shapeLogo,
    screenshots: [shape1, shape3, shape4, shape5, shape6, shape7],
    github: "https://github.com/Madrigal-Carl/shape-website",
    liveDemo: "",
    featured: true,
    completedAt: "2025-12-01",
    features: [
      "Lesson and activity management",
      "Student monitoring dashboard",
      "Automated grading system",
      "Awards and achievement management",
      "Semester and curriculum management",
      "Teacher and admin role management",
      "Exportable reports (Docx)",
    ],
    contributions: [
      "Frontend development (UI implementation and integration)",
      "Backend development (APIs, logic, and database design)",
      "System integration and feature implementation",
    ],
  },
  {
    id: 3,
    title: "CHL SmartSolutions",
    description:
      "A full-featured eCommerce and business management web application with CMS, inventory control, sales monitoring, and role-based access for customers, cashiers, technicians, and administrators. The system supports end-to-end operations including product management, service handling, order processing, and financial tracking to help businesses monitor performance and improve decision-making.",
    category: "web",
    buildTime: "5mo",
    techStack: ["Laravel", "Livewire", "PHP", "MySQL", "Git & GitHub"],
    thumbnail: chlLogo,
    screenshots: [chl1, chl2, chl3, chl4, chl5, chl6],
    github: "https://github.com/Madrigal-Carl/chlsmartsolutions",
    liveDemo: "",
    featured: true,
    completedAt: "2025-11-01",
    features: [
      "Role-based access control (Admin, Cashier, Technician, Customer)",
      "Inventory management system with stock tracking and updates",
      "Online order processing and tracking system",
      "Walk-in customer transaction system for cashiers",
      "Service task management and assignment for technicians",
      "Content Management System (CMS) for products and pages",
      "Sales tracking and reporting dashboard",
      "Expenses tracking and financial monitoring module",
      "Real-time order, sales, and staff activity monitoring",
      "Exportable reports (CSV/PDF format support)",
    ],
    contributions: [
      "Frontend development (UI implementation and Livewire integration)",
      "Backend development (API logic, business rules, and database design)",
      "System architecture design and full feature implementation",
    ],
  },
  {
    id: 4,
    title: "WindShieldRVS",
    description:
      "A web-based house vulnerability assessment system designed to evaluate the structural risk of one-storey residential houses against strong winds. The system analyzes house data and generates automated risk ratings to help users and administrators understand potential wind damage exposure. It includes location-based tracking, structured evaluation logic, and an admin dashboard for monitoring and reviewing assessments in real time.",
    category: "web",
    buildTime: "2mo",
    techStack: ["Laravel", "Livewire", "PHP", "MySQL", "Git & GitHub"],
    thumbnail: rvsLogo,
    screenshots: [rvs1, rvs2, rvs3, rvs4],
    github: "https://github.com/Madrigal-Carl/windshieldrvs",
    liveDemo: "",
    featured: false,
    completedAt: "2025-12-01",
    features: [
      "Automated vulnerability rating generation",
      "Strong wind risk evaluation system",
      "House location tracking and mapping",
      "Admin dashboard for monitoring assessment data",
      "Responsive web interface for multiple devices",
      "Exportable reports in PDF format",
    ],
    contributions: [
      "Frontend development (UI implementation and Livewire integration)",
      "Backend development (API logic, risk computation rules, and database design)",
      "System design, deployment, and full system implementation",
    ],
  },
  {
    id: 5,
    title: "CarScanAI: Car Brand Recognition System",
    description:
      "A web-based AI-powered car brand recognition system that identifies vehicle brands through image classification. The platform uses a custom-trained machine learning model developed to recognize over 15 car brands from uploaded vehicle images. It processes images in real time and provides instant prediction results, combining deep learning with a responsive web interface for a seamless user experience. The system also includes a full data pipeline from preprocessing to model training and deployment.",
    category: "ai",
    buildTime: "1mo",
    techStack: [
      "Python",
      "TensorFlow",
      "HTML",
      "Tailwind CSS",
      "JavaScript",
      "Git & GitHub",
      "Render",
    ],
    thumbnail: scanLogo,
    screenshots: [scan1, scan2, scan3],
    github: "https://github.com/Madrigal-Carl/CarScanAi",
    liveDemo: "https://carscanai.onrender.com/",
    featured: true,
    completedAt: "2025-12-01",
    features: [
      "Custom-trained AI model for car brand recognition",
      "Image classification using deep learning",
      "Supports 15+ car brands with high accuracy prediction",
      "Real-time prediction results from uploaded images",
    ],
    contributions: [
      "Frontend development and UI integration",
      "Backend development and AI model integration",
      "Custom machine learning model training and dataset preprocessing",
      "Deployment, testing, and system configuration",
    ],
  },
  {
    id: 6,
    title: "Tableo: Event Tabulation System",
    description:
      "A web-based event tabulation system designed to manage scoring, ranking, and result computation for competitions and organized events. The platform allows judges to submit scores, automatically processes and tallies results in real time, and handles ranking logic including tie-break resolution. It also includes event management features and exportable reports to support transparent and efficient competition handling.",
    category: "web",
    buildTime: "2mo",
    techStack: [
      "ReactJS",
      "ExpressJS",
      "Sequelize",
      "MySQL",
      "JavaScript",
      "Git & GitHub",
    ],
    thumbnail: tableoLogo,
    screenshots: [tableo1, tableo2, tableo3, tableo4, tableo5],
    github: "https://github.com/Madrigal-Carl/Tableo",
    liveDemo: "",
    featured: false,
    completedAt: "2026-03-01",
    features: [
      "Judge scoring and submission system",
      "Automated score tallying and ranking",
      "Tie-score handling and resolution",
      "Event management system",
      "Real-time results computation",
      "Exportable reports (PDF)",
    ],
    contributions: [
      "Backend development (API, scoring logic, and database design)",
      "Frontend support and UI adjustments for core features",
    ],
  },
  {
    id: 7,
    title: "SwiftDocs: Online Document Request System",
    description:
      "A web-based document request and tracking system designed for students to request, process, and monitor academic documents online. The system features role-based access for Admin, RMO, and Cashier, enabling structured handling of requests from submission to release. It supports document management, verification workflows, payment processing, and real-time tracking, along with reporting and sales monitoring for administrative oversight.",
    category: "web",
    buildTime: "2mo",
    techStack: [
      "ReactJS",
      "ExpressJS",
      "Zustand",
      "Sequelize",
      "MySQL",
      "JavaScript",
      "Git & GitHub",
      "Docker",
    ],
    thumbnail: swiftLogo,
    screenshots: [
      swift1,
      swift2,
      swift3,
      swift4,
      swift5,
      swift6,
      swift7,
      swift8,
      swift9,
    ],
    github: "https://github.com/Madrigal-Carl/SwiftDocs",
    liveDemo: "",
    featured: true,
    completedAt: "2026-04-01",
    features: [
      "Online document request system",
      "Real-time request tracking",
      "Role-based access control (Admin, RMO, Cashier)",
      "Document management system",
      "Document verification and release workflow",
      "Sales and analytics dashboard",
      "Exportable reports (PDF)",
    ],
    contributions: [
      "Full-stack development (frontend and backend implementation)",
      "System architecture, API design, and database design",
      "End-to-end feature development and integration",
    ],
  },
  {
    id: 8,
    title: "Project Store: Portfolio Showcase Website",
    description:
      "A modern portfolio showcase website designed to display projects, skills, technologies, and development experience in an organized and interactive interface. The design and layout are inspired by the Google Play Store, featuring a clean, card-based structure that makes browsing projects more intuitive and visually engaging. It focuses on presenting projects in a structured and user-friendly way with emphasis on clarity and accessibility.",
    category: "web",
    buildTime: "1mo",
    techStack: ["ReactJS", "Tailwind CSS", "JavaScript", "Git & GitHub", "Vercel"],
    thumbnail: projLogo,
    screenshots: [proj1, proj2, proj3],
    github: "https://github.com/Madrigal-Carl/Portfolio",
    liveDemo: "https://cm-portfolio-tan.vercel.app/",
    featured: false,
    completedAt: "2026-05-28",
    features: [
      "Responsive project portfolio showcase",
      "Technology stack presentation",
    ],
    contributions: [
      "Frontend development and UI implementation",
      "Responsive design and component architecture",
      "Project layout design inspired by Google Play Store UI",
    ],
  },
  {
    id: 9,
    title: "Task Manager: Full-Stack CRUD Application",
    description:
      "A full-stack task management application built to practice modern React development patterns and backend API integration. The application supports complete CRUD operations, pagination, filtering, and task status management. It leverages TanStack Query for efficient server-state management and caching, while React Hook Form and Zod provide a robust and scalable form validation workflow. The project focuses on learning best practices for building responsive, maintainable, and data-driven web applications.",
    category: "web",
    buildTime: "1d",
    techStack: [
      "ReactJS",
      "Tailwind CSS",
      "TanStack Query",
      "React Hook Form",
      "Zod",
      "JavaScript",
      "Express.js",
      "Node.js",
      "MongoDB",
      "Mongoose",
      "Git & GitHub",
    ],
    thumbnail: taskLogo,
    screenshots: [task1, task2, task3],
    github: "https://github.com/Madrigal-Carl/TaskManager",
    liveDemo: "https://task-manager-iota-peach.vercel.app/",
    featured: false,
    completedAt: "2026-06-20",
    features: [
      "CRUD operations",
      "Pagination, filtering, and search",
      "Form validation",
      "TanStack Query caching",
      "Responsive design",
      "REST API integration",
    ],

    contributions: [
      "Frontend development",
      "Backend development",
      "Database integration",
      "State management and caching",
      "Form validation",
    ],
  },
  {
    id: 10,
    title: "AgriCentral: Agricultural Resource Management Platform",
    description:
      "A centralized, role-based agricultural management platform designed to help agricultural offices move away from fragmented records and manual processes. The system streamlines disaster response and resource allocation by giving officials clear visibility into farmers, farms, equipment, livestock, and crops. It centralizes resource requests, incident reporting, and audit trails, with role-based access for different offices and personnel, and exportable reports to support faster, more transparent decision-making across regions and cooperatives.",
    category: "web",
    buildTime: "1.5mo",
    techStack: [
      "ReactJS",
      "ExpressJS",
      "Node.js",
      "MongoDB",
      "TanStack Query",
      "Tailwind CSS",
      "JavaScript",
      "Resend",
      "Lovable",
      "Render",
      "Vercel",
      "Git & GitHub",
      "Cloudinary",
      "Valkey",
    ],
    thumbnail: agriLogo,
    screenshots: [
      agri1,
      agri2,
      agri3,
      agri4,
      agri5,
      agri6,
      agri7,
      agri8,
      agri9,
      agri10,
      agri11,
      agri12,
      agri13,
      agri14,
      agri15,
      agri16,
      agri17,
      agri18,
      agri19,
      agri20,
    ],
    github: "https://github.com/Madrigal-Carl/AgriCentral",
    liveDemo: "https://agri-central-five.vercel.app/",
    featured: true,
    completedAt: "2026-08-01",
    features: [
      "Farmer profile and association registry",
      "Geo-tagged farm records with parcel-level detail",
      "Crop monitoring with yield estimate tracking",
      "Livestock inventory and distribution history",
      "Equipment tracking with ownership, usage, and maintenance logs",
      "Centralized resource request management (crops, equipment, livestock)",
      "Incident reporting for damages and disruptions",
      "Immutable audit logs for every action and decision",
      "Organization and cooperative management with role-based access control",
      "Real-time dashboard analytics across regions and operations",
      "Exportable reports for offices and decision-makers",
    ],
    contributions: [
      "Full-stack development (frontend and backend implementation)",
      "System architecture, API design, and database design",
      "Role-based access control and permissions design",
      "Report export functionality implementation",
      "End-to-end feature development and integration",
    ],
  },
];

export const isRecent = (completedAt) => {
  const now = new Date();
  const projectDate = new Date(completedAt);
  const twoMonthsAgo = new Date(
    now.getFullYear(),
    now.getMonth() - 2,
    now.getDate(),
  );
  return projectDate >= twoMonthsAgo;
};

export const getProjectsWithRecent = () => {
  return [...PROJECTS]
    .sort((a, b) => b.id - a.id)
    .map((project) => ({
      ...project,
      recent: isRecent(project.completedAt),
    }));
};
